### ISSUE TITLE
There needs to be a main program.

### ISSUE THREAD

**Issue by BB-Harris** [embeddedgyro/shakey-table#33]
We need an actual program that utilises our libraries to interface with the MPU6050, INA260, and MD20, to drive our anti-quake cup holder. That is, read accel and gyro data from the MPU6050, calculate the cup holder angle/position, then drive the MD20 to produce the required corrective torque from the motor, using the INA260 data as torque feedback data.

**Comment by genamag** [comment]
the main program is done and tested, everything works as intended after we  replaced faulty components

there is only a problem of occasional I2C errors, in sensor communication, but they do not disrupt the functioning of the main program and don't affect performance, as sensor readings are sent with very high freqeuncy

**Comment by genamag** [comment]
Because we fried the INA260 current sensor, we can only control the wheel with PID control from gyro readings, so there is no good control over the torque produced by the motor
