### ISSUE TITLE
Create a proper README file with hardware and software instruction 

### ISSUE THREAD

**Issue by genamag** [embeddedgyro/shakey-table#49]
Torin - CAD design
Gennady - Hardware setup
Adam - Software setup and installation
Jambu - Running Unit testing

**Comment by genamag** [comment]
Added a hardware description with all components and what they are doing + how to connect. Also created and added images of the circuitry and positioning of key components

**Comment by genamag** [comment]
yesterday we changed the position of the INA from before to after the motor to protect it from the reverse bias current created by the filter, so I need to reflect that in Wiki, change images and README in terms of this modification to the circuitry

**Comment by genamag** [comment]
@dalvador2 How is the CAD and INA software part doing? 
@Jambu1234 How is the Unit testing part doing? (don't forget about writing about CMake for them as well with instructions on how to run them)
@Adam-Englebright how is the MPU6050 and main program section doing?

Please, report on your progress

**Comment by BB-Harris** [comment]
The section on setting up the software is essentially done. I want to add details about the lines required in `/boot/firmware/config.txt`.

**Comment by Jambu1234** [comment]
Readme for Unit testing execution has been updated with the necessary cmake comments to run them.

**Comment by dalvador2** [comment]
closed #61
